check_keyboard_navigation(INPUT_ACTION.UI_NAVIGATE_LEFT, instance_left);
check_keyboard_navigation(INPUT_ACTION.UI_NAVIGATE_UP, instance_above);
check_keyboard_navigation(INPUT_ACTION.UI_NAVIGATE_RIGHT, instance_right);
check_keyboard_navigation(INPUT_ACTION.UI_NAVIGATE_DOWN, instance_below);